### ISSUE TITLE
Return key doesn't close modal when input field is focused in webview

### ISSUE THREAD

**Issue by andrejilderda** [jacopocolo/sketchplugin-webview-template#1]
Hi Jacopo,

Thanks for your work on this one! As you've described in the readme implementing a webview in a Sketch plugin is indeed challenging when you don't have any experience in developing OSX applications. I've been struggling with passing data to the webview before and your workaround seems like a huge help. 

I'm trying to use your code for improving one of my plugins [Resize Commands](https://github.com/ANGIstudio/Sketch-Resize-Commands). I'd like to close the  webview after the user pressed the enter key. In your code I see you took care of this with `[okButton setKeyEquivalent:"\r"]`. However, this does not work when an input field in the webview is focused. Do you have an idea of how to make this work?

Best,
Andre

**Comment by jacopocolo** [comment]
I wish I had an answer, I have the same exact problem and never actually found a solution. In theory that piece of code you mention should take care of binding the key to the button but it never worked.

I'll post in the Sketch developer mailing list asking for help and report back if I find something useful.

**Comment by andrejilderda** [comment]
Just wanted to let you know I've managed to achieve the above using:
https://github.com/mathieudutour/sketch-module-web-view
