### ISSUE TITLE
Different HTML pages how to achieve it jump

### ISSUE THREAD

**Issue by Nealyang** [jacopocolo/sketchplugin-webview-template#3]
I have two HTML pages, how to do it from page1 jump to page2 it

**Comment by jacopocolo** [comment]
Adding a second HTML page in the Resources folder and linking them together seems to be working fine from a quick test I did. 

<img width="296" alt="screen shot 2017-12-11 at 08 56 29" src="https://user-images.githubusercontent.com/1939567/33820791-55fd430a-de51-11e7-836b-960125f298f4.png">

In the case above ui.html and ui-2.html are connected together with a link and commands seemed to work fine in both pages.

**Comment by Nealyang** [comment]
Thanks Reply
